[package]
name = "bluee/projek-cl4six"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.4"
Networker = "leifstout/networker@0.2.1"

[server-dependencies]
ProfileService = "firecam702/profileservice@1.0.0"