[package]
name = "bluee/projek-cl4six"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
cmdr = "evaera/cmdr@1.12.0"
iris = "sirmallard/iris@2.4.1"
imgizmo = "jakeywastaken/imgizmo@3.6.0"
topbarplus = "1foreverhd/topbarplus@3.2.5"
bitbuffer = "brinkokevin/bitbuffer@1.0.1"

[server-dependencies]
profileservice = "firebird702/profileservice@1.1.0"